In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
cars = pd.read_csv("auto.csv")
cars.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0       130.0  3504.0          12.0    70   
1  15.0          8         350.0       165.0  3693.0          11.5    70   
2  18.0          8         318.0       150.0  3436.0          11.0    70   
3  16.0          8         304.0       150.0  3433.0          12.0    70   
4  17.0          8         302.0       140.0  3449.0          10.5    70   

   origin  
0       1  
1       1  
2       1  
3       1  
4       1

In [3]:
unique_region =cars["origin"].unique()
unique_region

array([1, 3, 2], dtype=int64)

1 = north america

2 = europe

3 = aisa

In [4]:
cars["cylinders"].unique()

array([8, 4, 6, 3, 5], dtype=int64)

In [5]:
dummy_cyl = pd.get_dummies(cars["cylinders"], prefix = "cyl")
dummy_year = pd.get_dummies(cars["year"], prefix = "year")

In [6]:
cars = pd.concat([cars,dummy_cyl, dummy_year], axis = 1)

In [7]:
cars.drop(["year", "cylinders"] ,axis = 1 , inplace = True)

In [8]:
cars.head()

mpg  displacement  horsepower  weight  acceleration  origin  cyl_3  cyl_4  \
0  18.0         307.0       130.0  3504.0          12.0       1      0      0   
1  15.0         350.0       165.0  3693.0          11.5       1      0      0   
2  18.0         318.0       150.0  3436.0          11.0       1      0      0   
3  16.0         304.0       150.0  3433.0          12.0       1      0      0   
4  17.0         302.0       140.0  3449.0          10.5       1      0      0   

   cyl_5  cyl_6  ...  year_73  year_74  year_75  year_76  year_77  year_78  \
0      0      0  ...        0        0        0        0        0        0   
1      0      0  ...        0        0        0        0        0        0   
2      0      0  ...        0        0        0        0        0        0   
3      0      0  ...        0        0        0        0        0        0   
4      0      0  ...        0        0        0        0        0        0   

   year_79  year_80  year_81  year_82  
0        0        0        0        0  
1        0        0        0        0  
2        0        0        0        0  
3        0        0        0        0  
4        0        0        0        0  

[5 rows x 24 columns]

In [9]:
shuffled_index = np.random.permutation(cars.index)
shuffled_index

array([147, 202,  91, 274, 306, 339,  83, 272, 267, 233, 162, 149, 318,
       231, 304, 203, 371,  75, 298, 205, 163, 278, 259, 263,  41, 264,
       221,  59, 145, 124, 218, 353, 239,  78, 225, 137,  22, 246,  37,
       356,  64,  69, 132,   5, 289, 120,  67,  82,  71, 327, 141, 150,
        87,   9, 329, 389,  95, 340,  89,  38, 197,  96, 123, 237, 349,
       214, 188, 369, 183, 159, 224, 310, 333, 193, 377, 232, 338, 359,
        62,  21, 151, 300, 208,  27, 241, 343, 146,  23,   3, 257,  43,
       283, 212,   6, 172, 370, 331,   8,  93, 134,  48, 170, 279, 286,
        39, 133,  30,  42, 360, 158, 112, 236, 171, 265, 366, 284,  26,
        20, 235, 247, 215, 326, 313, 177, 249,  36, 354, 254, 190, 164,
       100, 270, 373,  84, 186,  45, 125, 299,  56, 128, 260, 206, 168,
       130,  13, 180, 324,  68, 350, 207,  92, 288, 229, 142, 245, 113,
       131,  53,  76, 379,  57,  16,  14, 195, 230, 320, 293, 317, 139,
       227, 119, 252, 347, 390,  19, 374, 226, 266, 148, 268,  6

In [10]:
np.random.seed(123)
shuffled_cars = cars.iloc[shuffled_index]

In [11]:
cars.shape

(392, 24)

In [12]:
no_rows = shuffled_cars.shape[0]

In [13]:
train_index = int(392*.7)

In [14]:
train = shuffled_cars.iloc[:train_index]
test = shuffled_cars.iloc[train_index:]

In [15]:
(shuffled_cars["origin"]==1).unique()

array([False,  True])

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
cols = shuffled_cars.columns

In [18]:
features = []
for c in cols:
    if c.startswith("cyl") or c.startswith("year"):
        features.append(c)

In [22]:
models = {}
for origin in unique_region:
    model = LogisticRegression()
    model.fit(train[features], train["origin"] == origin)
    